name: test_app
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  freezed_annotation: ^2.0.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.1.11
  freezed: ^2.0.3
  json_serializable: ^6.2.0
